# JVM and Memory Configuration
org.gradle.native=false
org.gradle.jvmargs=-Xmx6G -XX:+UseParallelGC -XX:MaxMetaspaceSize=2G -XX:ReservedCodeCacheSize=512m -XX:+HeapDumpOnOutOfMemoryError

# Android & Kotlin Incremental Caching
android.useAndroidX=true
org.gradle.caching=true
org.gradle.parallel=true
org.gradle.configureondemand=true
org.gradle.vfs.watch=true
kotlin.incremental=true
kotlin.incremental.useClasspathSnapshot=true
kapt.incremental.apt=true
android.enableR8.fullMode=false
