# JVM and Memory Configuration
org.gradle.native=false
org.gradle.jvmargs=-Xmx4096m -XX:+UseParallelGC -XX:MaxMetaspaceSize=1024m -XX:ReservedCodeCacheSize=256m -XX:+HeapDumpOnOutOfMemoryError

# Android & Kotlin Incremental Caching
android.useAndroidX=true
org.gradle.caching=true
org.gradle.parallel=true
org.gradle.configureondemand=true
org.gradle.vfs.watch=false
kotlin.incremental=true
kotlin.incremental.useClasspathSnapshot=true
kapt.incremental.apt=true
android.enableR8.fullMode=false
